# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/share.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(417, 300)
        Form.setStyleSheet("QWidget {\n"
"    border-radius: 20px;\n"
"    background-color: rgb(220, 242, 255);\n"
"}")
        self.labelShare = QtWidgets.QLabel(Form)
        self.labelShare.setGeometry(QtCore.QRect(110, 20, 181, 20))
        font = QtGui.QFont()
        font.setFamily("Lato")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.labelShare.setFont(font)
        self.labelShare.setObjectName("labelShare")
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setGeometry(QtCore.QRect(10, 70, 291, 31))
        self.lineEdit.setStyleSheet("QLineEdit {\n"
"    border-radius: 15px;\n"
"    border: gray 1px solid;\n"
"    padding: 25px;\n"
"    background-color: white;\n"
"}")
        self.lineEdit.setObjectName("lineEdit")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(10, 130, 151, 17))
        font = QtGui.QFont()
        font.setFamily("Lato")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayoutWidget = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 160, 390, 80))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalScrollBar = QtWidgets.QScrollBar(self.verticalLayoutWidget)
        self.verticalScrollBar.setOrientation(QtCore.Qt.Vertical)
        self.verticalScrollBar.setObjectName("verticalScrollBar")
        self.verticalLayout.addWidget(self.verticalScrollBar)
        self.pushButtonCopy = QtWidgets.QPushButton(Form)
        self.pushButtonCopy.setGeometry(QtCore.QRect(10, 260, 80, 31))
        self.pushButtonCopy.setStyleSheet("QPushButton {\n"
"    border-radius: 15px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(0, 85, 255);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    \n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.pushButtonCopy.setObjectName("pushButtonCopy")
        self.pushButtonDone = QtWidgets.QPushButton(Form)
        self.pushButtonDone.setGeometry(QtCore.QRect(310, 260, 80, 31))
        self.pushButtonDone.setStyleSheet("QPushButton {\n"
"    border-radius: 15px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(0, 85, 255);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    \n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.pushButtonDone.setObjectName("pushButtonDone")
        self.comboBox = QtWidgets.QComboBox(Form)
        self.comboBox.setEnabled(True)
        self.comboBox.setGeometry(QtCore.QRect(308, 70, 91, 30))
        self.comboBox.setStyleSheet("QComboBox {\n"
"    border-radius: 15px;\n"
"    border: gray 1px solid;\n"
"    padding:  0 10px;\n"
"    color: black;\n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        self.comboBox.setEditable(False)
        self.comboBox.setCurrentText("Restricted")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.labelShare.setText(_translate("Form", "Share \"DOC_NAME\""))
        self.lineEdit.setPlaceholderText(_translate("Form", "Add people"))
        self.label_2.setText(_translate("Form", "People With Access"))
        self.pushButtonCopy.setText(_translate("Form", "Copy URL"))
        self.pushButtonDone.setText(_translate("Form", "Done"))
        self.comboBox.setItemText(0, _translate("Form", "Restricted"))
        self.comboBox.setItemText(1, _translate("Form", "Reader"))
        self.comboBox.setItemText(2, _translate("Form", "Writer"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
